# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-anemometer"
BBFILE_PATTERN_meta-anemometer = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-anemometer = "6"

LAYERDEPENDS_meta-anemometer = "core"
LAYERSERIES_COMPAT_meta-anemometer = "scarthgap"
