[package]
name = "comms-project"
version = "0.1.0"
edition = "2021"
description = "Rust data logger for STM32 wind sensor"
repository = "https://github.com/zwarres1/solid-state-anemometer/"

[dependencies]
anyhow = "1.0.100"
[target.'cfg(any(target_arch = "arm", target_arch = "aarch64"))'.dependencies]
serialport = { version = "4.8.1", default-features = false }
