require conf/distro/poky.conf
DISTRO = "anemometer-os"
DISTRO_NAME = "Anemometer Custom Linux"

ENABLE_UART = "1"
IMAGE_ROOTFS_EXTRA_SPACE = "1048576"
CORE_IMAGE_EXTRA_INSTALL += "wpa-supplicant iw"
LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"
EXTRA_IMAGE_FEATURES += "ssh-server-dropbear"
IMAGE_INSTALL:append = " wind-logger"

# Disable login terminal on serial ports so the Rust app can use them
SERIAL_CONSOLES = ""

# Switch to systemd
DISTRO_FEATURES:append = " systemd usrmerge"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_initscripts = ""
PACKAGECONFIG:append:pn-systemd = " networkd resolved"
APPEND += "net.ifnames=0"
ROOT_HOME = "/root"

# Keep downloads and compiled cache outside the build directory
DL_DIR = "${TOPDIR}/../downloads"
SSTATE_DIR = "${TOPDIR}/../sstate-cache"

# Get around crate blocking of wget from bitbake
FETCHCMD_wget = "/usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate --user-agent='bitbake/2.0'"